<a href="https://colab.research.google.com/github/william-alexandre/Tech-Foundation-Coding/blob/main/Perceptron_Aprendizagem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#importar NumPy
import numpy as np

In [49]:
# Definir a matriz de Entrada
entradas = np.array([[0,0],
                     [0,1],
                     [1,0],
                     [1,1]])
entradas

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [50]:
#Definir a Classe Verdade
#saidas = np.array([0,0,0,1]) # Operador AND
#saidas = np.array([0,1,1,1]) # Operador OR
saidas = np.array([0,1,1,0]) # Operador XOR
saidas

array([0, 1, 1, 0])

In [51]:
# Definir os pesos iniciais
pesos = np.array([0.0,0.0])
pesos

array([0., 0.])

In [52]:
# Definir a variável taxaAprendizagem
taxaAprendizagem = 0.1

In [53]:
# Definir a Função de Ativação Step Function
def stepFunction(soma):
    if (soma >= 1):
        return 1
    return 0

In [54]:
# Definir a função Soma
def somaFunction(entradas):
  #Multiplicar os pesos
  return entradas.dot(pesos)

In [55]:
# Definindo a Função de treino do Modelo
def treinarModelo():
  erroTotal = 1
  while (erroTotal != 0):
    erroTotal = 0
    for i in range(len(saidas)):

      #Chamada da Funçaõ soma para aplicação dos pesos
      soma = somaFunction(entradas[i])

      #Chamada da Função de Ativação
      saidaCalculada = stepFunction(soma)

      #Calcular o erro
      erro = abs(saidas[i] - saidaCalculada)

      #Adicionar o resultado na variavel erroTotal
      erroTotal += erro

      #Realizar os ajustes nos pesos
      for j in range(len(pesos)):

        #FÓRMULA DE ATUALIZAÇÃO DOS PESOS
        # peso(n + 1) = peso(n) + (taxaAprendizagem * entrada * erro)
        pesos[j] = pesos[j] + (taxaAprendizagem * entradas[i][j] * erro)

       #Peso Atualizado
        print('Peso atualizado: ' + str(pesos[j]))

      print ('Total de erros: '+ str(erroTotal))

In [56]:
# Executar o treino do mode
treinarModelo()
print('Rede Neural Treinada')
print(stepFunction(somaFunction(entradas[0])))
print(stepFunction(somaFunction(entradas[1])))
print(stepFunction(somaFunction(entradas[2])))
print(stepFunction(somaFunction(entradas[3])))

A saída de streaming foi truncada nas últimas 5000 linhas.
Peso atualizado: 55061.499999479245
Total de erros: 1
Peso atualizado: 55061.499999479245
Peso atualizado: 55061.499999479245
Total de erros: 0
Peso atualizado: 55061.499999479245
Peso atualizado: 55061.499999479245
Total de erros: 0
Peso atualizado: 55061.499999479245
Peso atualizado: 55061.499999479245
Total de erros: 0
Peso atualizado: 55061.599999479244
Peso atualizado: 55061.599999479244
Total de erros: 1
Peso atualizado: 55061.599999479244
Peso atualizado: 55061.599999479244
Total de erros: 0
Peso atualizado: 55061.599999479244
Peso atualizado: 55061.599999479244
Total de erros: 0
Peso atualizado: 55061.599999479244
Peso atualizado: 55061.599999479244
Total de erros: 0
Peso atualizado: 55061.69999947924
Peso atualizado: 55061.69999947924
Total de erros: 1
Peso atualizado: 55061.69999947924
Peso atualizado: 55061.69999947924
Total de erros: 0
Peso atualizado: 55061.69999947924
Peso atualizado: 55061.69999947924
Total de er

KeyboardInterrupt: 

In [48]:
pesos

array([1.1, 1.1])